create table "private"."ai_settings" (
    "id" integer not null default 1,
    "openai_api_key" text,
    "model" text,
    "updated_at" timestamp with time zone not null default now(),
    constraint "ai_settings_pkey" primary key ("id"),
    constraint "ai_settings_singleton" check (id = 1)
);

create table "private"."ai_conversations" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "title" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    constraint "ai_conversations_pkey" primary key ("id"),
    constraint "ai_conversations_sales_id_fkey" foreign key ("sales_id") references "public"."sales"("id") on delete cascade
);

create table "private"."ai_messages" (
    "id" bigint generated by default as identity not null,
    "conversation_id" bigint not null,
    "message" jsonb not null,
    "created_at" timestamp with time zone not null default now(),
    constraint "ai_messages_pkey" primary key ("id"),
    constraint "ai_messages_conversation_id_fkey" foreign key ("conversation_id") references "private"."ai_conversations"("id") on delete cascade
);

create index "ai_conversations_sales_id_idx" on "private"."ai_conversations" using btree ("sales_id", "updated_at" desc);

create index "ai_messages_conversation_id_idx" on "private"."ai_messages" using btree ("conversation_id", "id");

alter table "private"."ai_settings" enable row level security;

alter table "private"."ai_conversations" enable row level security;

alter table "private"."ai_messages" enable row level security;
